### PR TITLE
updated readme and samples

### PR DESCRIPTION
**Pull request by ajoslin103**
Hi Bronto,

Here's the updated readme and sample example

hope you like it

al;

### CODE REVIEW

**Comment by brontolinux** [comment]
Hey!
I haven't forgotten this PR, I'm just a bit swamped at the moment, and I can't just merge it because I'd like to make some changes myself first. I'll look at it ASAP, thanks for submitting it!
-- bronto

**Comment by ajoslin103** [comment]
not to worry - I just remembered about it last night

can’t believe it’s Thursday already

do you have a favorite(s) in  the cfengine policy frameworks ?

al;

**Comment by brontolinux** [comment]
Hey!

I just wanted to let you know that I'm working on this. It's taking some time because I'm not merging things straight away, but also shuffling, fixing and improving things in the process. I'm moving forward though.

As for the policy frameworks, it's not really a topic for a pull request ;-) but NCF and EFL are good.

**Comment by ajoslin103** [comment]
great, thanks.

**Comment by brontolinux** [comment]
Some progress today, too. The README file is almost ready

**Comment by brontolinux** [comment]
This is now merged in master, congratulations!
I'm now closing the pull request. Thanks for contributing!

**Comment by brontolinux** [comment]
Uhm... I actually see that some of my changes have been lost in the process, for some reason. Damn... I'll have to fix them again :-(

**Comment by brontolinux** [comment]
All right, seems fine now.

**Comment by ajoslin103** [comment]
looks good

I see two typos I must have left in there

masterfiles/sample.cf

The bundle agent sample in thiss file will create and hand a simple list to the henc module and also apply a promise that will evaluate bundle agent manage that, in turn, will update the /etc/motd file.

should be

masterfiles/sample.cf

The bundle agent sample in this file will create and hand a simple list to the henc module and also apply a promise that will evaluate bundle agent managed that, in turn, will update the /etc/motd file.

thiss  >>  this

manage >>  managed

al;

**Comment by brontolinux** [comment]
On 02/04/15 12:51, allen joslin wrote:

> I see two typos I must have left in there

It could have been me as well.

Anyway: fixed ;-) Thanks for reporting the typos.

Ciao
-- bronto

**Pull request closed without merging**
